/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate via Telegram Login Widget
         * @description Validates the Telegram Login Widget payload (HMAC-SHA256 + freshness check on `auth_date`). On success, issues a session JWT as an HttpOnly cookie and returns the resolved `User` object.
         */
        post: operations["telegramAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invalidate the current session
         * @description Idempotent — clears the session cookie if present, returns 204 regardless of authentication state. No 401 is returned.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the authenticated user
         * @description Returns the currently logged-in user identified by the session cookie.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spendings/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get today's spending breakdown
         * @description Returns the grand total and per-category breakdown for the current calendar day. "Today" is computed using the server's configured timezone (TZ env var) to match the Telegram bot's `/today` command. Categories are ordered by total descending.
         */
        get: operations["getTodayBreakdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description An authenticated PaymentChecker user (sourced from Telegram identity). */
        User: {
            /**
             * Format: int64
             * @description Telegram user ID.
             * @example 123456789
             */
            id: number;
            /**
             * @description User's first name as provided by Telegram.
             * @example Alice
             */
            first_name: string;
            /**
             * @description User's last name (optional).
             * @example Smith
             */
            last_name?: string;
            /**
             * @description Telegram @username without the leading "@" (optional).
             * @example alice_smith
             */
            username?: string;
            /**
             * @description URL of the user's Telegram profile photo (optional).
             * @example https://t.me/i/userpic/320/alice.jpg
             */
            photo_url?: string;
        };
        /** @description Aggregated spending total for a single category. */
        CategorySum: {
            /**
             * @description Free-text category name as stored by the user.
             * @example Food
             */
            category: string;
            /**
             * Format: double
             * @description Sum of spending amounts for this category (unitless).
             * @example 2340.5
             */
            total: number;
        };
        /** @description Spending breakdown for the current calendar day, computed in the server's configured timezone (TZ env var). */
        TodayBreakdown: {
            /**
             * Format: double
             * @description Grand total across all categories for today.
             * @example 3410
             */
            total: number;
            /** @description Per-category totals, ordered by total descending. */
            categories: components["schemas"]["CategorySum"][];
        };
        /** @description Fields forwarded from the Telegram Login Widget callback. The `hash` field is an HMAC-SHA256 of the sorted field list signed with the bot token; the backend MUST verify it and reject payloads where `auth_date` is older than 24 hours. */
        TelegramAuthPayload: {
            /**
             * Format: int64
             * @description Telegram user ID.
             * @example 123456789
             */
            id: number;
            /** @example Alice */
            first_name: string;
            /** @example Smith */
            last_name?: string;
            /** @example alice_smith */
            username?: string;
            /** @example https://t.me/i/userpic/320/alice.jpg */
            photo_url?: string;
            /**
             * Format: int64
             * @description Unix timestamp (seconds) of when the user authorized the widget.
             * @example 1745539200
             */
            auth_date: number;
            /**
             * @description HMAC-SHA256 verification hash produced by Telegram.
             * @example a1b2c3d4e5f6...
             */
            hash: string;
        };
        /** @description Standard error envelope. */
        Error: {
            /**
             * @description Machine-readable error code.
             * @example INVALID_HASH
             */
            code: string;
            /**
             * @description Human-readable error description.
             * @example Telegram auth hash is invalid or expired.
             */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    telegramAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramAuthPayload"];
            };
        };
        responses: {
            /** @description Authentication successful. Session cookie is set. */
            200: {
                headers: {
                    /** @description Sets a `session` cookie containing the signed JWT. Lifetime: 7 days (`Max-Age=604800`). */
                    "Set-Cookie": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Invalid HMAC signature or stale `auth_date`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cleared. Cookie is expired. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Missing or invalid session cookie. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTodayBreakdown: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Today's breakdown. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayBreakdown"];
                };
            };
            /** @description Missing or invalid session cookie. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
